# Generated by Django 4.0 on 2022-01-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(default='2022-01-03'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
