# Generated by Django 3.2 on 2022-01-06 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_schedule', '0003_alter_schedule_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='schedules',
            new_name='user',
        ),
    ]
